var Calculadora = {
  uno: document.getElementById("1"),
  dos: document.getElementById("2"),
  tres: document.getElementById("3"),
  cuatro: document.getElementById("4"),
  cinco: document.getElementById("5"),
  seis: document.getElementById("6"),
  siete: document.getElementById("7"),
  ocho: document.getElementById("8"),
  nueve: document.getElementById("9"),
  cero: document.getElementById("0"),
  on: document.getElementById("on"),
  sign: document.getElementById("sign"),
  dividido: document.getElementById("dividido"),
  por: document.getElementById("por"),
  menos: document.getElementById("menos"),
  mas: document.getElementById("mas"),
  punto: document.getElementById("punto"),
  igual: document.getElementById("igual"),
  resultado: document.getElementById("display"),
  teclas: document.getElementsByClassName("tecla"),
  operandoA: 0,
  operandoB: 0,
  operacion: ""
}
